FEATURE_FLAGS = {
    "ENABLE_TEMPLATE_PROCESSING": True,
}

ENABLE_PROXY_FIX = True
SECRET_KEY = "YOUR_OWN_RANDOM_GENERATED_STRING"
SQLALCHEMY_DATABASE_URI = "postgresql://superset:superset@postgres:5432"
WTF_CSRF_ENABLED = False
TALISMAN_ENABLED = False